apiVersion: apps/v1
kind: Deployment
metadata:
  name: maple-glow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maple-glow
  template:
    metadata:
      labels:
        app: maple-glow
    spec:
      containers:
        - name: maple-glow
          image: maple-glow-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: maple-glow-secrets
                  key: MONGODB_PASS
