apiVersion: v1
kind: Secret
metadata:
  name: maple-glow-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USER:PASSWORD@example.mongodb.net/?retryWrites=true&w=majority"
  SESSION_SECRET: "replace-with-at-least-32-random-characters"
  EMAIL_PASSWORD: "replace-with-an-app-password"
